services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n-CVdC.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-yourname.onrender.com/
      - key: N8N_PORT
        value: 5678
